#!/bin/sh -eu
# vim: fdm=marker cms=\ #\ %s

if test $# -lt 1; then
  echo "Usage: $0 {-h|--help|<tag>}" >/dev/stderr
  exit 1
fi

bsapiurl=https://api.suse.de/
pkgname=build_rpm_from_image
gitname=containment-rpm
pkgdir=Devel:StudioOnline:containment_common_packages/$pkgname
dloadurl=https://github.com/openSUSE/$gitname
specfile=$gitname.spec
tag=$1
version=${tag#v}
tarball=$gitname-$version.tar.gz

case $tag in
-h|--help)
  printf "%s\n" \
    "$0 <tag>" \
    "" \
    "Updates $pkgdir" "from $dloadurl @ <tag>." >&2
  exit 0
  ;;
esac

osc() # {{{
{
  set -eu
  command osc -A $bsapiurl "${1+$@}"
} # }}}
fetch() # {{{
{
  set -eu
  local tag=${1?}
  wget -qO $tarball $dloadurl/tarball/"$@"
} # }}}
repack() # {{{
{
  set -eu
  local tarball=${1?}
  local dir=${tarball%.tar.gz}
  mkdir $dir
  tar -xzf $tarball --strip-components=1 -C $dir
  tar -czf $tarball $dir
  rm -rf $dir
} # }}}
extract() # {{{
{
  set -eu
  local tarball=${1?}
  local dir=${tarball%.tar.gz}
  shift
  tar -xzf $tarball --strip-components=1 $@
} # }}}
update() # {{{
{
  local specfile=${1?} version=${2?}
  sed -ri '/^Version:/s/__VERSION__/'$version'/' $specfile
} # }}}
exithook() # {{{
{
  pwd
  ls -a
  #rm -rf $root
} # }}}

trap exithook EXIT
root=$(mktemp -d)
echo $root
cd $root
osc co $pkgdir
fetch $tag
repack $tarball
rm -f $pkgdir/$gitname-*.tar.gz
mv $tarball $pkgdir
cd $pkgdir
extract $tarball $specfile
update $specfile $version
echo osc build
osc ar $gitname-*.tar.gz
echo osc ci
