#!/bin/sh -eu
# vim: fdm=marker cms=\ #\ %s

if test $# -lt 1; then
  echo "Usage: $0 {-h|--help|<tag>}" >/dev/stderr
  exit 1
fi

project=Devel:StudioOnline:containment_common_packages
project=home:rneuhauser
pkgname=containment-rpm
gitname=$pkgname
dloadurl=https://github.com/openSUSE/$gitname
bsapiurl=https://api.suse.de/
pkgdir=$project/$pkgname
specfile=$gitname.spec
tag=$1
version=${tag#v}
tarball=$gitname-$version.tar.gz

case $tag in
-h|--help)
  printf "%s\n" \
    "$0 <tag>" \
    "" \
    "Updates $pkgdir" "from $dloadurl @ <tag>." >&2
  exit 0
  ;;
esac

osc() # {{{
{
  set -eu
  command osc -A $bsapiurl "${1+$@}"
} # }}}
fetch() # {{{
{
  set -eu
  local tag=${1?}
  wget -qO $tarball $dloadurl/tarball/"$@"
} # }}}
repack() # {{{
{
  set -eu
  local tarball=${1?}
  local dir=${tarball%.tar.gz}
  mkdir $dir
  tar -xzf $tarball --strip-components=1 -C $dir
  tar -czf $tarball $dir
  rm -rf $dir
} # }}}
extract() # {{{
{
  set -eu
  local tarball=${1?}
  local file=${tarball%.tar.gz}/${2?}
  shift
  tar -xzf $tarball --strip-components=1 $file
} # }}}
update() # {{{
{
  case $1 in
  *.spec)  update_specfile "$@" ;;
  *.tar.*) update_tarball "$@" ;;
  esac
} # }}}
update_specfile() # {{{
{
  local specfile=${1?} version=${2?}
  sed -r '/^Version:/s/__VERSION__/'$version'/' $specfile.in > $specfile
} # }}}
update_tarball() # {{{
{
  local tarball=${1?} rewrite=0
  if test -f $pkgdir/$tarball; then
    rewrite=1
  fi
  if test 0 -eq $rewrite && test -f $pkgdir/$gitname-*.tar.gz; then
    osc rm $pkgdir/$gitname-*.tar.gz
  fi
  mv $tarball $pkgdir
  if test 0 -eq $rewrite; then
    osc add $pkgdir/$tarball
  fi
} # }}}
exithook() # {{{
{
  pwd
  ls -a
  #rm -rf $root
} # }}}

trap exithook EXIT
root=$(mktemp -d)
echo $root
cd $root
osc co $pkgdir
fetch $tag
repack $tarball
update $tarball
cd $pkgdir
extract $tarball $specfile.in
update $specfile $version
#osc build
osc ci
